FROM frrouting/frr:latest
RUN echo 'service integrated-vtysh-config' > /etc/frr/vtysh.conf \
 && sed -i 's/\(bgpd\|ospfd\|isisd\)=no/\1=yes/g' /etc/frr/daemons
RUN apk add mandoc man-pages bridge iproute2 tcpdump vim
COPY script /script
